[package]
name = "intricate"
version = "0.3.2"
edition = "2021"
license = "MIT"
authors = ["Gabriel Miranda"]
keywords = ["neural-networks", "machine-learning", "backpropagation"]
description = "A GPU accelerated library that creates/trains/runs machine learning prediction models in safe Rust code."
repository = "https://github.com/gabrielmfern/intricate"
readme = "README.md"

[dependencies]
rayon = "1.5.3"
rand = "0.8.5"
savefile-derive="0.10"
savefile="0.10"
opencl3="0.8.1"
intricate-macros="0.3.7"

[[example]]
name = "xor"