[package]
name = "intricate"
version = "0.1.0"
edition = "2021"
license = "MIT"
keywords = ["neural-networks", "machine-learning", "backpropagation"]
description = "A GPU accelerated library that creates/trains/runs neural networks in pure safe Rust code."
repository = "https://github.com/gabrielmfern/intricate"
readme = "README.md"

[dependencies]
rayon = "1.5.3"
rand = "0.8.5"
wgpu = "0.13.1"
async-trait = "0.1.56"
pollster = "0.2.5"
